app/accounts/urls.py
from accounts import views

from django.urls import path

app_name = 'account'

urlpatterns = [
    # path('my-profile/<int:pk>/', views.MyProfile.as_view(), name='my-profile'),
    path('my-profile/', views.MyProfile.as_view(), name='my-profile'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('activate/account/<uuid:activation_key>/', views.ActivateAccount.as_view(), name='activate-account'),
]

app/currency/urls.py
from currency.views import (
    RateListView, RateDetailView,
    rate_create, RateUpdateView,
    RateDeleteView, CreateContactUs,
    LatestRates,
    # RateListApi,
)

from django.urls import path

app_name = 'currency'

urlpatterns = [
    path('rate/latest/', LatestRates.as_view(), name='rate-latest'),
    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),
    path('rate/create/', rate_create, name='rate-create'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),

    # path('api/rates/', RateListApi.as_view()),

    path('contact-us/create/', CreateContactUs.as_view(), name='contact-us-create'),
]

app/settings/urls.py
from currency.views import index
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.conf import settings

# from api.views import RateList, RateDetails

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('rates/', RateList.as_view()),
    # path('rates/<int:pk>/', RateDetails.as_view()),

    path('api/v1/', include('api.v1.urls')),
    path('', index, name='index'),
    path('auth/', include('django.contrib.auth.urls')), # new
    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

app/currency/models.py
from django.db import models
from currency import choices


class Bank(models.Model):
    name = models.CharField(max_length=64)
    code_name = models.CharField(
        max_length=64,
        unique=True,
    )
    url = models.URLField()
    original_url = models.URLField()

    def __str__(self):
        return f'Bank {self.name}'


class Rate(models.Model):
    # def get_{field_name}_display()
    type = models.PositiveSmallIntegerField(choices=choices.RATE_TYPE_CHOICES)
    sale = models.DecimalField(max_digits=5, decimal_places=2)
    buy = models.DecimalField(max_digits=5, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    bank = models.ForeignKey(
        Bank,
        related_name='rates',
        on_delete=models.CASCADE,
    )
    # bank = models.ForeignKey('currency.Bank')

    def __str__(self):
        return f'Rate id: {self.id} {self.bank_id}'


class ContactUs(models.Model):
    email_from = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.CharField(max_length=1024)
    created = models.DateTimeField(auto_now_add=True)

    # def save(self, *args, **kwargs):
    #     print('ContactUs Model save')
    #     return super().save(*args, **kwargs)

class Analytics(models.Model):
    path = models.CharField(max_length=255)
    counter = models.PositiveBigIntegerField()
    request_method = models.PositiveSmallIntegerField(
        choices=choices.REQUEST_METHOD_CHOICES)

    class Meta:
        unique_together = [
            ['path', 'request_method'],
        ]

"""
OtO - OneToOne
OTM - OneToMany
MtM - many To Many
"""

app/currency/forms.py
from django import forms

from currency.models import Rate, ContactUs


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'type',
            'sale',
            'buy',
            'bank',
        )


class ContactUsCreate(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'email_from',
            'subject',
            'message',
        )

    # def save(self, commit=True):
    #     print('Form Save\n' * 10)
    #     return super().save(commit)

app/currency/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, View, TemplateView
from django.core.mail import send_mail
from currency import choices, consts
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator

from currency.utils import generate_password as gp
from currency.tasks import send_email_in_background

from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest

from currency.forms import RateForm, ContactUsCreate
from currency.models import Rate, ContactUs, Bank
from django_filters.views import FilterView
from currency.filters import RateFilter


def generate_password(request):
    password = gp()
    return HttpResponse(password)


def index(request):
    return render(request, 'index.html')


class RateListView(FilterView):
    template_name = 'rate_list.html'
    queryset = Rate.objects.all().select_related('bank')
    paginate_by = 25
    filterset_class = RateFilter


class RateDetailView(DetailView):
    template_name = 'rate_details.html'
    queryset = Rate.objects.all()


def rate_create(request):

    if request.method == 'POST':
        csrftoken = request.COOKIES.get('csrftoken')

        lock = cache.add(csrftoken, True, 10)

        if lock:
            form_data = request.POST
            form = RateForm(form_data)
            if form.is_valid():
                form.save()
                # return HttpResponseRedirect(reverse('currency:rate-list'))
                return redirect('currency:rate-list')
        else:
            return HttpResponseBadRequest('Too many requests')

    elif request.method == 'GET':
        form = RateForm()

    context = {
        'message': 'Rate Create',
        'form': form,
        'count': Rate.objects.count(),
    }
    return render(request, 'rate_create.html', context=context)


class RateUpdateView(UpdateView):
    queryset = Rate.objects.all()
    template_name = 'rate_update.html'
    success_url = reverse_lazy('currency:rate-list')
    form_class = RateForm


class RateDeleteView(DeleteView):
    queryset = Rate.objects.all()
    success_url = reverse_lazy('currency:rate-list')


def get_latest_rates():
    if consts.CACHE_KEY_LATEST_RATES in cache:
        return cache.get(consts.CACHE_KEY_LATEST_RATES)

    object_list = []
    for bank in Bank.objects.all():
        for ct_value, ct_display in choices.RATE_TYPE_CHOICES:
            latest_rate = Rate.objects \
                .filter(type=ct_value, bank=bank).order_by('-created').first()
            if latest_rate is not None:
                object_list.append(latest_rate)

    cache.set(consts.CACHE_KEY_LATEST_RATES, object_list, 60 * 60 * 8)
    return object_list


# @method_decorator(cache_page(60 * 60 * 8), name='dispatch')
class LatestRates(TemplateView):
    template_name = 'latest_rates.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = get_latest_rates()
        return context


class CreateContactUs(CreateView):
    model = ContactUs
    fields = (
        'email_from',
        'subject',
        'message',
    )
    # form_class = ContactUsCreate
    success_url = reverse_lazy('index')

    # template_name = 'contact-us-create.html'

    def form_valid(self, form):
        data = form.cleaned_data
        body = f'''
        From: {data['email_from']}
        Topic: {data['subject']}

        Message:
        {data['message']}
        '''

        send_email_in_background.delay(body)

        # from .tasks import print_hello_world
        # print_hello_world.delay()

        return super().form_valid(form)


# class RateListApi(View):
#     def get(self, request):
#         rates = Rate.objects.all()
#         results = []
#         for rate in rates:
#             results.append({
#                 'id': rate.id,
#                 'sale': float(rate.sale),
#                 'buy': float(rate.buy),
#                 'bank': rate.bank_id,
#             })
#         import json
#         return JsonResponse(results, safe=False)
#         # return HttpResponse(json.dumps(results), content_type='application/json')

app/currency/templates/includes/navbar.html
{% load active_link_tags %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% active_link 'index' %}" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% active_link 'currency:rate-list' %}" href="{% url 'currency:rate-list' %}">Rate List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% active_link 'currency:rate-latest' %}" href="{% url 'currency:rate-latest' %}">Latest Rates</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% active_link 'currency:contact-us-create' %}" href="{% url 'currency:contact-us-create' %}">Contact Us</a>
                </li>
            </ul>
            {% if request.user.is_authenticated %}
                <span class="navbar-text"><a href="{% url 'logout' %}">Logout</a><a href="{% url 'account:my-profile' %}">My Profile</a></span>
            {% else %}
                <span class="navbar-text"><a href="{% url 'login' %}">Login</a> <a href="{% url 'account:signup' %}">Sign Up</a></span>
            {% endif %}
        </div>
    </div>
</nav>

app/currency/templates/includes/pagination.html
{% load i18n %}
<nav>
    <ul class="paginator pagination">
        <li class="index">
            {% blocktrans with current_page=page.number total_page=page.paginator.num_pages %}Page {{ current_page }} of
                {{ total_page }}{% endblocktrans %}
        </li>

        {% if page.has_previous %}
            <li class="page previous">
                <a href="?page={{ page.previous_page_number }}{{ GET_string }}"
                   title="{% trans "More recent entries" %}">&laquo;</a>
            </li>
        {% endif %}

        {% for page_number in begin %}
            <li class="page-item page{% ifequal page.number page_number %} current{% endifequal %}">
                {% ifequal page.number page_number %}
                    {{ page_number }}
                {% else %}
                    <a href="?page={{ page_number }}{{ GET_string }}"
                       class="page-link"
                       title="{% trans "Entries page" %} {{ page_number }}">{{ page_number }}</a>
                {% endifequal %}
            </li>
        {% endfor %}

        {% if middle %}
            <li class="ellipsis">&hellip;</li>
            {% for page_number in middle %}
                <li class="page{% ifequal page.number page_number %} current{% endifequal %}">
                    {% ifequal page.number page_number %}
                        {{ page_number }}
                    {% else %}
                        <a href="?page={{ page_number }}{{ GET_string }}"
                           title="{% trans "Entries page" %} {{ page_number }}">{{ page_number }}</a>
                    {% endifequal %}
                </li>
            {% endfor %}
        {% endif %}

        {% if end %}
            <li class="ellipsis">&hellip;</li>
            {% for page_number in end %}
                <li class="page{% ifequal page.number page_number %} current{% endifequal %}">
                    {% ifequal page.number page_number %}
                        {{ page_number }}
                    {% else %}
                        <a href="?page={{ page_number }}{{ GET_string }}"
                           title="{% trans "Entries page" %} {{ page_number }}">{{ page_number }}</a>
                    {% endifequal %}
                </li>
            {% endfor %}
        {% endif %}

        {% if page.has_next %}
            <li class="page next">
                <a href="?page={{ page.next_page_number }}{{ GET_string }}"
                   title="{% trans "More old entries" %}">&raquo;</a>
            </li>
        {% endif %}
    </ul>
</nav>