app/accounts/urls.py
from accounts import views

from django.urls import path

app_name = 'account'

urlpatterns = [
    # path('my-profile/<int:pk>/', views.MyProfile.as_view(), name='my-profile'),
    path('my-profile/', views.MyProfile.as_view(), name='my-profile'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('activate/account/<uuid:activation_key>/', views.ActivateAccount.as_view(), name='activate-account'),
]

app/currency/urls.py
from currency.views import (
    RateListView, RateDetailView,
    rate_create, RateUpdateView,
    RateDeleteView, CreateContactUs,
    LatestRates,
    # RateListApi,
)

from django.urls import path

app_name = 'currency'

urlpatterns = [
    path('rate/latest/', LatestRates.as_view(), name='rate-latest'),
    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),
    path('rate/create/', rate_create, name='rate-create'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),

    # path('api/rates/', RateListApi.as_view()),

    path('contact-us/create/', CreateContactUs.as_view(), name='contact-us-create'),
]

app/settings/urls.py
from currency.views import index
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.conf import settings

# from api.views import RateList, RateDetails

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('rates/', RateList.as_view()),
    # path('rates/<int:pk>/', RateDetails.as_view()),

    path('api/v1/', include('api.v1.urls')),
    path('', index, name='index'),
    path('auth/', include('django.contrib.auth.urls')), # new
    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

app/currency/models.py
from django.db import models
from currency import choices


class Bank(models.Model):
    name = models.CharField(max_length=64)
    code_name = models.CharField(
        max_length=64,
        unique=True,
    )
    url = models.URLField()
    original_url = models.URLField()

    def __str__(self):
        return f'Bank {self.name}'


class Rate(models.Model):
    # def get_{field_name}_display()
    type = models.PositiveSmallIntegerField(choices=choices.RATE_TYPE_CHOICES)
    sale = models.DecimalField(max_digits=5, decimal_places=2)
    buy = models.DecimalField(max_digits=5, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    bank = models.ForeignKey(
        Bank,
        related_name='rates',
        on_delete=models.CASCADE,
    )
    # bank = models.ForeignKey('currency.Bank')

    def __str__(self):
        return f'Rate id: {self.id} {self.bank_id}'


class ContactUs(models.Model):
    email_from = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.CharField(max_length=1024)
    created = models.DateTimeField(auto_now_add=True)

    # def save(self, *args, **kwargs):
    #     print('ContactUs Model save')
    #     return super().save(*args, **kwargs)

class Analytics(models.Model):
    path = models.CharField(max_length=255)
    counter = models.PositiveBigIntegerField()
    request_method = models.PositiveSmallIntegerField(
        choices=choices.REQUEST_METHOD_CHOICES)

    class Meta:
        unique_together = [
            ['path', 'request_method'],
        ]

"""
OtO - OneToOne
OTM - OneToMany
MtM - many To Many
"""

app/currency/forms.py
from django import forms

from currency.models import Rate, ContactUs


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'type',
            'sale',
            'buy',
            'bank',
        )


class ContactUsCreate(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'email_from',
            'subject',
            'message',
        )

    # def save(self, commit=True):
    #     print('Form Save\n' * 10)
    #     return super().save(commit)

app/currency/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, View, TemplateView
from django.core.mail import send_mail
from currency import choices, consts
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator

from currency.utils import generate_password as gp
from currency.tasks import send_email_in_background

from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest

from currency.forms import RateForm, ContactUsCreate
from currency.models import Rate, ContactUs, Bank
from django_filters.views import FilterView
from currency.filters import RateFilter


def generate_password(request):
    password = gp()
    return HttpResponse(password)


def index(request):
    return render(request, 'index.html')


class RateListView(FilterView):
    template_name = 'rate_list.html'
    queryset = Rate.objects.all().select_related('bank')
    paginate_by = 25
    filterset_class = RateFilter


class RateDetailView(DetailView):
    template_name = 'rate_details.html'
    queryset = Rate.objects.all()


def rate_create(request):

    if request.method == 'POST':
        csrftoken = request.COOKIES.get('csrftoken')

        lock = cache.add(csrftoken, True, 10)

        if lock:
            form_data = request.POST
            form = RateForm(form_data)
            if form.is_valid():
                form.save()
                # return HttpResponseRedirect(reverse('currency:rate-list'))
                return redirect('currency:rate-list')
        else:
            return HttpResponseBadRequest('Too many requests')

    elif request.method == 'GET':
        form = RateForm()

    context = {
        'message': 'Rate Create',
        'form': form,
        'count': Rate.objects.count(),
    }
    return render(request, 'rate_create.html', context=context)


class RateUpdateView(UpdateView):
    queryset = Rate.objects.all()
    template_name = 'rate_update.html'
    success_url = reverse_lazy('currency:rate-list')
    form_class = RateForm


class RateDeleteView(DeleteView):
    queryset = Rate.objects.all()
    success_url = reverse_lazy('currency:rate-list')


def get_latest_rates():
    if consts.CACHE_KEY_LATEST_RATES in cache:
        return cache.get(consts.CACHE_KEY_LATEST_RATES)

    object_list = []
    for bank in Bank.objects.all():
        for ct_value, ct_display in choices.RATE_TYPE_CHOICES:
            latest_rate = Rate.objects \
                .filter(type=ct_value, bank=bank).order_by('-created').first()
            if latest_rate is not None:
                object_list.append(latest_rate)

    cache.set(consts.CACHE_KEY_LATEST_RATES, object_list, 60 * 60 * 8)
    return object_list


# @method_decorator(cache_page(60 * 60 * 8), name='dispatch')
class LatestRates(TemplateView):
    template_name = 'latest_rates.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = get_latest_rates()
        return context


class CreateContactUs(CreateView):
    model = ContactUs
    fields = (
        'email_from',
        'subject',
        'message',
    )
    # form_class = ContactUsCreate
    success_url = reverse_lazy('index')

    # template_name = 'contact-us-create.html'

    def form_valid(self, form):
        data = form.cleaned_data
        body = f'''
        From: {data['email_from']}
        Topic: {data['subject']}

        Message:
        {data['message']}
        '''

        send_email_in_background.delay(body)

        # from .tasks import print_hello_world
        # print_hello_world.delay()

        return super().form_valid(form)


# class RateListApi(View):
#     def get(self, request):
#         rates = Rate.objects.all()
#         results = []
#         for rate in rates:
#             results.append({
#                 'id': rate.id,
#                 'sale': float(rate.sale),
#                 'buy': float(rate.buy),
#                 'bank': rate.bank_id,
#             })
#         import json
#         return JsonResponse(results, safe=False)
#         # return HttpResponse(json.dumps(results), content_type='application/json')

app/currency/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"#}
{#          rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">#}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">#}
</head>
<body>

{% include 'includes/navbar.html' %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% block main_content %}
{% endblock main_content %}

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

app/currency/templates/dummy.html
{% extends template %}

app/currency/templates/index.html
{% extends 'base.html' %}

{% block main_content %}
    {#    <a>Rates</a>#}
    {#    <a>Contact Us</a>#}
    <div class="container">
        <div class="row">
            <div class="col">
                1 of 2
            </div>
            <div class="col">
                2 of 2
            </div>
        </div>
        <div class="row">
            <div class="col">
                1 of 3
            </div>
            <div class="col">
                2 of 3
            </div>
            <div class="col">
                3 of 3
            </div>
        </div>
    </div>
{% endblock main_content %}

app/currency/templates/latest_rates.html
{% extends 'base.html' %}
{% load cache %}

{% block main_content %}

    {% cache 500 latest_rates %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">ID</th>
            <th scope="col">Type</th>
            <th scope="col">Sale</th>
            <th scope="col">Buy</th>
            <th scope="col">Source Name</th>
            <th scope="col">Created</th>
        </tr>
        </thead>
        <tbody>
        {% for rate in object_list %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ rate.id }}</td>
            <td>{{ rate.get_type_display }}</td>
            <td>{{ rate.sale }}</td>
            <td>{{ rate.buy }}</td>
            <td>{{ rate.bank.name }}</td>
            <td>{{ rate.created }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endcache %}
{% endblock main_content %}

app/currency/templates/rate_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

Count: {{ count }}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send</button>
</form>

</body>
</html>

app/currency/templates/rate_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<p>ID: {{ object.id }}</p>
<p>Buy: {{ object.buy }}</p>
<p>Sale: {{ object.sale }}</p>

</body>
</html>

app/currency/templates/rate_list.html
{% extends 'base.html' %}
{% load pagination %}

{% block main_content %}
    <a href="/currency/rate/create/">Create Rate</a>

    <form method="get">
        {{ filter.form.as_p }}
        <button type="submit" class="btn btn-primary">
            <span class="glyphicon glyphicon-search"></span> Apply Filters
        </button>
    </form>

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">ID</th>
            <th scope="col">Type</th>
            <th scope="col">Sale</th>
            <th scope="col">Buy</th>
            <th scope="col">Source Name</th>
            <th scope="col">Created</th>
            <th scope="col">Details</th>
            <th scope="col">Edit</th>
        </tr>
        </thead>
        <tbody>
        {% for rate in object_list %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ rate.id }}</td>
            <td>{{ rate.get_type_display|lower }}</td>
            <td>{{ rate.sale }}</td>
            <td>{{ rate.buy }}</td>
            <td>{{ rate.bank.name }}</td>
            <td>{{ rate.created }}</td>
            <td><a href="{% url 'currency:rate-details' pk=rate.id %}">Details</a></td>
            <td><a href="{% url 'currency:rate-update' pk=rate.id %}">Edit</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
      {% pagination page_obj %}
    {% endif %}
{% endblock main_content %}

app/currency/templates/rate_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

Instance: {{ form.instance.id }}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send</button>
</form>

<a href="/currency/rate/delete/{{ form.instance.id }}/">Delete</a>

</body>
</html>